name: [Build & Push to Dockerhub]
on:
  push:
  workflow_dispach:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: phtfreire/simple-api:latest